language: python
cache: pip

python:
  - "3.6"
  - "3.7"

env:
  - DJANGO="django>=2.2,<3.0"
  - DJANGO="django>=3.0,<3.1"

branches:
  only:
    - master

install:
  - pip install $DJANGO
  - pip install -e git+git://github.com/openwisp/django-netjsongraph#egg=django-netjsongraph
  - python setup.py -q develop
  - pip install -r requirements-test.txt

script:
  - openwisp-utils-qa-checks --migration-path "./openwisp_network_topology" --migration-module topology
  - coverage run --source=openwisp_network_topology runtests.py

after_success:
  coveralls
